name: publish

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    publish:
        if: github.repository == 'thingsapi/things.py'
        runs-on: ubuntu-latest
        environment: github-pages
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - name: Publish to PyPi
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: |
                  pip install wheel twine
                  make upload
